// Date: 2016.02.20. 21:15:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.tom.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBottle extends ModelBase
{
  //fields
    ModelRenderer bottleBase;
    ModelRenderer bottleside1;
    ModelRenderer bottleside2;
    ModelRenderer bottleside3;
    ModelRenderer bottleside4;
    ModelRenderer bottleTop1;
    ModelRenderer bottleTop2;
    ModelRenderer bottleTop3;
    ModelRenderer bottleTop4;
    ModelRenderer bottleTop5;
    ModelRenderer bottleTop6;
    ModelRenderer bottleTop7;
    ModelRenderer bottleTop8;
    ModelRenderer bottleCup2;
    ModelRenderer bottleCup3;
    ModelRenderer bottleCup4;
    ModelRenderer bottleCup5;
  
  public ModelBottle()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      bottleBase = new ModelRenderer(this, 20, 18);
      bottleBase.addBox(0F, 0F, 0F, 6, 1, 6);
      bottleBase.setRotationPoint(-3F, 23F, -3F);
      bottleBase.setTextureSize(64, 64);
      bottleBase.mirror = true;
      setRotation(bottleBase, 0F, 0F, 0F);
      bottleside1 = new ModelRenderer(this, 20, 18);
      bottleside1.addBox(0F, 0F, 0F, 1, 6, 6);
      bottleside1.setRotationPoint(-4F, 17F, -3F);
      bottleside1.setTextureSize(64, 64);
      bottleside1.mirror = true;
      setRotation(bottleside1, 0F, 0F, 0F);
      bottleside2 = new ModelRenderer(this, 20, 18);
      bottleside2.addBox(0F, 0F, 0F, 1, 6, 6);
      bottleside2.setRotationPoint(3F, 17F, -3F);
      bottleside2.setTextureSize(64, 64);
      bottleside2.mirror = true;
      setRotation(bottleside2, 0F, 0F, 0F);
      bottleside3 = new ModelRenderer(this, 20, 18);
      bottleside3.addBox(0F, 0F, 0F, 6, 6, 1);
      bottleside3.setRotationPoint(-3F, 17F, 3F);
      bottleside3.setTextureSize(64, 64);
      bottleside3.mirror = true;
      setRotation(bottleside3, 0F, 0F, 0F);
      bottleside4 = new ModelRenderer(this, 20, 18);
      bottleside4.addBox(0F, 0F, 0F, 6, 6, 1);
      bottleside4.setRotationPoint(-3F, 17F, -4F);
      bottleside4.setTextureSize(64, 64);
      bottleside4.mirror = true;
      setRotation(bottleside4, 0F, 0F, 0F);
      bottleTop1 = new ModelRenderer(this, 20, 18);
      bottleTop1.addBox(0F, 0F, 0F, 6, 1, 2);
      bottleTop1.setRotationPoint(-3F, 16F, -3F);
      bottleTop1.setTextureSize(64, 64);
      bottleTop1.mirror = true;
      setRotation(bottleTop1, 0F, 0F, 0F);
      bottleTop2 = new ModelRenderer(this, 20, 18);
      bottleTop2.addBox(0F, 0F, 0F, 6, 1, 2);
      bottleTop2.setRotationPoint(-3F, 16F, 1F);
      bottleTop2.setTextureSize(64, 64);
      bottleTop2.mirror = true;
      setRotation(bottleTop2, 0F, 0F, 0F);
      bottleTop3 = new ModelRenderer(this, 20, 18);
      bottleTop3.addBox(0F, 0F, 0F, 2, 1, 2);
      bottleTop3.setRotationPoint(1F, 16F, -1F);
      bottleTop3.setTextureSize(64, 64);
      bottleTop3.mirror = true;
      setRotation(bottleTop3, 0F, 0F, 0F);
      bottleTop4 = new ModelRenderer(this, 20, 18);
      bottleTop4.addBox(0F, 0F, 0F, 2, 1, 2);
      bottleTop4.setRotationPoint(-3F, 16F, -1F);
      bottleTop4.setTextureSize(64, 64);
      bottleTop4.mirror = true;
      setRotation(bottleTop4, 0F, 0F, 0F);
      bottleTop5 = new ModelRenderer(this, 20, 18);
      bottleTop5.addBox(0F, 0F, 0F, 4, 1, 1);
      bottleTop5.setRotationPoint(-2F, 14F, 1F);
      bottleTop5.setTextureSize(64, 64);
      bottleTop5.mirror = true;
      setRotation(bottleTop5, 0F, 0F, 0F);
      bottleTop6 = new ModelRenderer(this, 20, 18);
      bottleTop6.addBox(0F, 0F, 0F, 1, 1, 2);
      bottleTop6.setRotationPoint(1F, 14F, -1F);
      bottleTop6.setTextureSize(64, 64);
      bottleTop6.mirror = true;
      setRotation(bottleTop6, 0F, 0F, 0F);
      bottleTop7 = new ModelRenderer(this, 20, 18);
      bottleTop7.addBox(0F, 0F, 0F, 1, 1, 2);
      bottleTop7.setRotationPoint(-2F, 14F, -1F);
      bottleTop7.setTextureSize(64, 64);
      bottleTop7.mirror = true;
      setRotation(bottleTop7, 0F, 0F, 0F);
      bottleTop8 = new ModelRenderer(this, 20, 18);
      bottleTop8.addBox(0F, 0F, 0F, 4, 1, 1);
      bottleTop8.setRotationPoint(-2F, 14F, -2F);
      bottleTop8.setTextureSize(64, 64);
      bottleTop8.mirror = true;
      setRotation(bottleTop8, 0F, 0F, 0F);
      bottleCup2 = new ModelRenderer(this, 20, 18);
      bottleCup2.addBox(0F, 0F, 0F, 3, 1, 1);
      bottleCup2.setRotationPoint(-1.5F, 15F, 0.5F);
      bottleCup2.setTextureSize(64, 64);
      bottleCup2.mirror = true;
      setRotation(bottleCup2, 0F, 0F, 0F);
      bottleCup3 = new ModelRenderer(this, 20, 18);
      bottleCup3.addBox(0F, 0F, 0F, 3, 1, 1);
      bottleCup3.setRotationPoint(-1.5F, 15F, -1.5F);
      bottleCup3.setTextureSize(64, 64);
      bottleCup3.mirror = true;
      setRotation(bottleCup3, 0F, 0F, 0F);
      bottleCup4 = new ModelRenderer(this, 24, 20);
      bottleCup4.addBox(0F, 0F, 0F, 1, 1, 1);
      bottleCup4.setRotationPoint(-1.5F, 15F, -0.5F);
      bottleCup4.setTextureSize(64, 64);
      bottleCup4.mirror = true;
      setRotation(bottleCup4, 0F, 0F, 0F);
      bottleCup5 = new ModelRenderer(this, 24, 20);
      bottleCup5.addBox(0F, 0F, 0F, 1, 1, 1);
      bottleCup5.setRotationPoint(0.5F, 15F, -0.5F);
      bottleCup5.setTextureSize(64, 64);
      bottleCup5.mirror = true;
      setRotation(bottleCup5, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    bottleBase.render(f5);
    bottleside1.render(f5);
    bottleside2.render(f5);
    bottleside3.render(f5);
    bottleside4.render(f5);
    bottleTop1.render(f5);
    bottleTop2.render(f5);
    bottleTop3.render(f5);
    bottleTop4.render(f5);
    bottleTop5.render(f5);
    bottleTop6.render(f5);
    bottleTop7.render(f5);
    bottleTop8.render(f5);
    bottleCup2.render(f5);
    bottleCup3.render(f5);
    bottleCup4.render(f5);
    bottleCup5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity ent)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,ent);
  }
  public void renderStatic(float f5){
	  bottleBase.render(f5);
	    bottleside1.render(f5);
	    bottleside2.render(f5);
	    bottleside3.render(f5);
	    bottleside4.render(f5);
	    bottleTop1.render(f5);
	    bottleTop2.render(f5);
	    bottleTop3.render(f5);
	    bottleTop4.render(f5);
	    bottleTop5.render(f5);
	    bottleTop6.render(f5);
	    bottleTop7.render(f5);
	    bottleTop8.render(f5);
	    bottleCup2.render(f5);
	    bottleCup3.render(f5);
	    bottleCup4.render(f5);
	    bottleCup5.render(f5);
  }
}
