package com.tom.core.research;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.item.ItemStack;

import net.minecraftforge.fml.common.registry.GameRegistry;

import com.tom.api.research.IScanningInformation.ScanningInformation;
import com.tom.api.research.Research;
import com.tom.api.research.ResearchComplexity;
import com.tom.apis.TomsModUtils;
import com.tom.core.CoreInit;
import com.tom.core.TMResource;
import com.tom.core.TMResource.CraftingMaterial;
import com.tom.core.TMResource.Type;
import com.tom.energy.EnergyInit;
import com.tom.factory.FactoryInit;
import com.tom.recipes.AdvancedCraftingRecipes;
import com.tom.storage.StorageInit;

public class ResearchLoader {
	public static Research researchAcids, researchPower, researchPower2, hammer, mortar, bronzeAge, basicBoiler, basicBronzeMachines, bronzeAlloySmelter, bronzePlateBlender, refinedBricks, cokeOven, blastFurnace, advancedTank, steelBoiler, steelFurnace, rubberProcessing, soldering, basicTurbine, multimeter, lvCable, batteryBox, basicLvMachines, wireProcessing, speedUpgrade, lvPlateBlender, lvAlloySmelter, waterCollector, pump, fluidTransposer, eSolderingStation, solarPanel, industrialBlastFurnace, mvTransformer, mvCable, mvCircuit, mvMachines, refinery, multiblockComponents, plasticProcessing, electrolyzer, centrifuge, advancedMultiblockParts, hvTransformer, advancedCircuit,
	hvCable, hvMachines, eliteTank, ultimateTank, limitableChest, advancedExtruder, mvTurbine, charger, configurator, geoThermalBoiler, geoThermalGenerator, liquidFueledBoiler, liquidFueledSteelBoiler, liquidFueledGenerator;

	public static void init(){
		CoreInit.log.info("Loading Researches...");
		researchAcids = new Research("acids", TMResource.SULFUR.getStackNormal(Type.DUST)).setResearchTime(200).setRequiredItems(TomsModUtils.getItemStackList(TMResource.SULFUR.getStackNormal(Type.DUST,6), new ItemStack(Items.IRON_INGOT,2), TMResource.COPPER.getStackNormal(Type.INGOT,2),TMResource.TIN.getStackNormal(Type.INGOT,2)));
		researchPower = new Research("power", new ItemStack(Items.REDSTONE)).setResearchTime(500).setRequiredItems(TomsModUtils.getItemStackList(new ItemStack(Items.REDSTONE,4))).setRequiredScans(AdvancedCraftingRecipes.getScanningList(new ScanningInformation(Blocks.REDSTONE_WIRE,0),new ScanningInformation(Blocks.REDSTONE_WIRE,15)));
		researchPower2 = new Research("power2", new ItemStack(Items.REDSTONE)).setResearchTime(1000).setRequiredScans(AdvancedCraftingRecipes.getScanningList(new ScanningInformation(CoreInit.oreCopper,0),new ScanningInformation(CoreInit.oreZinc,0),new ScanningInformation(Blocks.REDSTONE_ORE,0),new ScanningInformation(Blocks.IRON_ORE,0),new ScanningInformation(Blocks.LIT_REDSTONE_ORE,0))).setRequiredItems(TomsModUtils.getItemStackList(new ItemStack(Items.REDSTONE),TMResource.ZINC.getStackNormal(Type.PLATE, 12), TMResource.COPPER.getStackNormal(Type.PLATE, 12), CraftingMaterial.ACID_PAPER.getStackNormal(12))).addParent(researchAcids).addParent(researchPower);
		hammer = new Research("hammer", TMResource.COAL.getHammerStack(1)).addRequiredScan(Blocks.IRON_BLOCK, 0).addRequiredItem(new ItemStack(Items.FLINT, 4)).setResearchTime(150);
		mortar = new Research("mortar", new ItemStack(CoreInit.mortarAndPestle)).addParent(hammer).addRequiredItem(new ItemStack(Items.FLINT, 2)).addRequiredItem(CraftingMaterial.STONE_BOWL.getStackNormal(2)).setResearchTime(200);
		bronzeAge = new Research("bronzeAge", TMResource.BRONZE.getStackNormal(Type.PLATE)).addParent(mortar).addParent(researchAcids).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.PLATE, 2)).addRequiredItem(new ItemStack(Blocks.BRICK_BLOCK)).addRequiredScan(Blocks.CLAY, 0).addRequiredScan(Blocks.HARDENED_CLAY, -1).setResearchTime(200);
		basicBoiler = new Research("basicBoiler", new ItemStack(FactoryInit.basicBoiler)).setResearchTime(300).addParent(bronzeAge).addRequiredItem(new ItemStack(Items.CLAY_BALL, 2)).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.PLATE, 4)).addRequiredItem(new ItemStack(Blocks.BRICK_BLOCK, 2)).addRequiredScan(Blocks.FURNACE, -1).addRequiredScan(Blocks.LIT_FURNACE, -1);
		basicBronzeMachines = new Research("basicBronzeMachines", new ItemStack(FactoryInit.steamFurnace)).setResearchTime(300).addParent(basicBoiler).addRequiredItem(new ItemStack(Blocks.FURNACE)).addRequiredItem(new ItemStack(Items.CLAY_BALL, 2)).addRequiredItem(new ItemStack(Blocks.BRICK_BLOCK, 2));
		bronzeAlloySmelter = new Research("bronzeAlloySmelter", new ItemStack(FactoryInit.steamAlloySmelter)).setResearchTime(350).addParent(basicBronzeMachines).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.DUST)).addRequiredItem(TMResource.COPPER.getStackNormal(Type.INGOT)).addRequiredItem(new ItemStack(Blocks.FURNACE));
		bronzePlateBlender = new Research("bronzePlateBlender", new ItemStack(FactoryInit.steamPlateBlender)).setResearchTime(350).addParent(basicBronzeMachines).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.PLATE, 2)).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.INGOT, 3));
		refinedBricks = new Research("refinedBricks", CraftingMaterial.REFINED_BRICK.getStackNormal()).setResearchTime(400).addParent(researchPower).addParent(bronzeAlloySmelter).addParent(bronzePlateBlender).addRequiredItem(new ItemStack(Items.CLAY_BALL, 10)).addRequiredItem(new ItemStack(Items.BRICK, 2)).addRequiredItem(new ItemStack(Items.NETHERBRICK)).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.PLATE));
		cokeOven = new Research("cokeOven", new ItemStack(FactoryInit.cokeOven)).addParent(refinedBricks).addRequiredItem(new ItemStack(Blocks.COAL_BLOCK)).addRequiredItem(new ItemStack(Blocks.SAND, 16)).addRequiredItem(new ItemStack(Items.BRICK, 2)).setResearchTime(500).addRequiredScan(Blocks.SAND, 0);
		blastFurnace = new Research("blastFurnace", new ItemStack(FactoryInit.blastFurnace)).addParent(cokeOven).addRequiredItem(new ItemStack(Items.MAGMA_CREAM)).setResearchTime(550).addRequiredItem(new ItemStack(Blocks.SOUL_SAND, 4)).addRequiredScan(Blocks.SOUL_SAND, 0).addRequiredItem(new ItemStack(Items.NETHERBRICK)).addRequiredScan(Blocks.NETHER_BRICK, -1);
		steelBoiler = new Research("advBoiler", new ItemStack(FactoryInit.advBoiler)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.INGOT, 4)).addRequiredItem(new ItemStack(Blocks.FURNACE)).setResearchTime(600).addParent(blastFurnace);
		steelFurnace = new Research("advSteamFurnace", new ItemStack(FactoryInit.advSteamFurnace)).addParent(steelBoiler).addRequiredItem(new ItemStack(FactoryInit.steamFurnace)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 4)).setResearchTime(700);
		rubberProcessing = new Research("rubberProcessing", CraftingMaterial.BOTTLE_OF_RUBBER.getStackNormal()).addParent(blastFurnace).addRequiredItem(new ItemStack(FactoryInit.steamFurnace)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 4)).addRequiredItem(CraftingMaterial.BOTTLE_OF_RUBBER.getStackNormal(2)).setResearchTime(600).addRequiredScan(CoreInit.rubberWood, -1).addRequiredScan(CoreInit.rubberLeaves, -1).addRequiredScan(CoreInit.rubberSapling, -1);
		soldering = new Research("soldering", new ItemStack(FactoryInit.steamSolderingStation)).setResearchTime(650).addParent(rubberProcessing).addRequiredItem(CraftingMaterial.SOLDERING_ALLOY.getStackNormal(3)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 2));
		basicTurbine = new Research("basicTurbine", new ItemStack(EnergyInit.steamTurbine)).addParent(soldering).addParent(steelBoiler).setResearchTime(700).addRequiredItem(TMResource.COPPER.getStackNormal(Type.CABLE, 16)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal(2)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 5)).addParent(researchPower2);
		multimeter = new Research("multimeter", new ItemStack(EnergyInit.multimeter)).addParent(basicTurbine).setResearchTime(700).addRequiredItem(new ItemStack(Items.COMPASS)).addRequiredItem(new ItemStack(Items.REDSTONE, 10)).addRequiredItem(TMResource.COPPER.getStackNormal(Type.CABLE));
		lvCable = new Research("lvCable", new ItemStack(EnergyInit.lvCable)).addParent(basicTurbine).setResearchTime(800).addRequiredItem(TMResource.COPPER.getStackNormal(Type.CABLE, 10)).addRequiredItem(CraftingMaterial.RUBBER.getStackNormal(5)).addRequiredItem(new ItemStack(Items.REDSTONE));
		batteryBox = new Research("batteryBox", new ItemStack(EnergyInit.batteryBox)).addParent(lvCable).setResearchTime(800).addRequiredItem(new ItemStack(Items.REDSTONE, 5)).addRequiredItem(TMResource.LEAD.getStackNormal(Type.INGOT)).addRequiredItem(TMResource.COPPER.getStackNormal(Type.INGOT, 3));
		basicLvMachines = new Research("basicLvMachines", new ItemStack(FactoryInit.crusher)).addParent(lvCable).setResearchTime(900).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addRequiredItem(new ItemStack(Items.FLINT, 3)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal(3)).addRequiredItem(new ItemStack(Items.REDSTONE, 6));
		wireProcessing = new Research("wireProcessingLv", new ItemStack(FactoryInit.wireMill)).addParent(basicLvMachines).setResearchTime(1000).addRequiredItem(TMResource.COPPER.getStackNormal(Type.CABLE, 20)).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal());
		speedUpgrade = new Research("speedUpgrade", new ItemStack(FactoryInit.speedUpgrade)).addParent(basicLvMachines).setResearchTime(2000).addRequiredItem(new ItemStack(Blocks.REDSTONE_BLOCK, 16)).addRequiredItem(new ItemStack(Blocks.REDSTONE_ORE)).addRequiredItem(TMResource.BLUE_METAL.getStackNormal(Type.INGOT, 3)).addRequiredItem(CraftingMaterial.UPGRADE_FRAME.getStackNormal(2)).setComplexity(ResearchComplexity.ADVANCED);
		lvPlateBlender = new Research("lvPlateBlender", new ItemStack(FactoryInit.plateBlendingMachine)).setResearchTime(1000).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal()).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addParent(basicLvMachines).addRequiredItem(new ItemStack(Items.DIAMOND));
		lvAlloySmelter = new Research("lvAlloySmelter", new ItemStack(FactoryInit.alloySmelter)).setResearchTime(1000).addParent(basicLvMachines).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal()).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addRequiredItem(TMResource.ELECTRUM.getStackNormal(Type.INGOT, 3));
		waterCollector = new Research("waterCollector", new ItemStack(FactoryInit.waterCollector)).setResearchTime(700).addParent(basicBronzeMachines).addRequiredItem(new ItemStack(Items.WATER_BUCKET)).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.INGOT));
		eSolderingStation = new Research("eSolderingStation", new ItemStack(FactoryInit.solderingStation)).setResearchTime(1100).addParent(lvAlloySmelter).addRequiredItem(CraftingMaterial.SOLDERING_ALLOY.getStackNormal(4)).addRequiredItem(CraftingMaterial.CUPRONICKEL_HEATING_COIL.getStackNormal()).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal()).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic));
		industrialBlastFurnace = new Research("industrialBlastFurnace", new ItemStack(FactoryInit.industrialBlastFurnace)).setResearchTime(1200).addParent(eSolderingStation).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addRequiredItem(CraftingMaterial.CUPRONICKEL_HEATING_COIL.getStackNormal(4)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal(2)).addRequiredItem(new ItemStack(CoreInit.MachineFrameSteel));
		pump = new Research("pump", new ItemStack(FactoryInit.pump)).setResearchTime(1000).addParent(basicLvMachines).addRequiredItem(new ItemStack(CoreInit.itemPump, 2)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal()).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic));
		fluidTransposer = new Research("fluidTransposer", new ItemStack(FactoryInit.fluidTransposer)).addParent(basicLvMachines).addRequiredItem(new ItemStack(CoreInit.itemPump, 2)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal()).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addRequiredItem(new ItemStack(StorageInit.tankBasic)).setResearchTime(1100);
		advancedTank = new Research("advTank", new ItemStack(StorageInit.tankAdv)).setResearchTime(500).addParent(blastFurnace).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 4)).addRequiredItem(new ItemStack(Blocks.GLASS, 32)).addRequiredItem(new ItemStack(StorageInit.tankBasic));
		solarPanel = new Research("solarPanel", new ItemStack(EnergyInit.solarPanel)).setResearchTime(1300).addParent(eSolderingStation).addRequiredItem(new ItemStack(Items.DYE, 4, EnumDyeColor.BLUE.getDyeDamage())).addRequiredItem(CraftingMaterial.SILICON_PLATE.getStackNormal(4)).addRequiredItem(new ItemStack(Items.REDSTONE, 4));
		mvTransformer = new Research("mvTransformer", new ItemStack(EnergyInit.transformerLMV)).setResearchTime(1500).addParent(eSolderingStation).addRequiredItem(TMResource.COPPER.getStackNormal(Type.COIL, 4)).addRequiredItem(new ItemStack(Items.IRON_INGOT, 2)).addRequiredItem(TMResource.ELECTRUM.getStackNormal(Type.COIL, 2)).addRequiredItem(new ItemStack(Items.REDSTONE));
		mvCable = new Research("mvCable", new ItemStack(EnergyInit.mvCable)).setResearchTime(1500).addParent(mvTransformer).addRequiredItem(CraftingMaterial.RUBBER.getStackNormal(4)).addRequiredItem(TMResource.ELECTRUM.getStackNormal(Type.CABLE));
		mvCircuit = new Research("mvCircuit", CraftingMaterial.NORMAL_CIRCUIT.getStackNormal()).setResearchTime(1800).addParent(mvTransformer).addRequiredItem(new ItemStack(Items.REDSTONE, 20)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal(5)).addRequiredItem(CraftingMaterial.SILICON_PLATE.getStackNormal(3)).addRequiredItem(TMResource.COPPER.getStackNormal(Type.COIL));
		mvMachines = new Research("mvMachines", new ItemStack(FactoryInit.crusher)).setResearchTime(2000).addParent(mvCable).addParent(mvCircuit).addRequiredItem(CraftingMaterial.NORMAL_CIRCUIT.getStackNormal(4)).addRequiredItem(new ItemStack(EnergyInit.transformerLMV)).addRequiredItem(new ItemStack(CoreInit.MachineFrameSteel)).addRequiredItem(TMResource.ELECTRUM.getStackNormal(Type.CABLE, 5));
		refinery = new Research("refinery", new ItemStack(FactoryInit.refinery)).setResearchTime(2500).addParent(basicLvMachines).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 10)).addRequiredItem(TMResource.ALUMINUM.getStackNormal(Type.PLATE, 4)).addRequiredItem(new ItemStack(CoreInit.MachineFrameSteel)).addRequiredItem(new ItemStack(Blocks.GLASS, 20));
		multiblockComponents = new Research("multiblockComponents", new ItemStack(FactoryInit.MultiblockCase)).addParent(refinery).addParent(mvMachines).addRequiredItem(TMResource.ALUMINUM.getStackNormal(Type.PLATE, 16)).addRequiredItem(new ItemStack(CoreInit.MachineFrameAluminum)).addRequiredItem(CraftingMaterial.NORMAL_CIRCUIT.getStackNormal());
		electrolyzer = new Research("electrolyzer", new ItemStack(FactoryInit.Electrolyzer)).setResearchTime(2000).addParent(multiblockComponents).addRequiredItem(new ItemStack(FactoryInit.MultiblockCase)).addRequiredItem(CraftingMaterial.NORMAL_CIRCUIT.getStackNormal(4)).addRequiredItem(TMResource.COAL.getStackNormal(Type.GEM, 32)).addRequiredItem(TMResource.ALUMINUM.getStackNormal(Type.PLATE, 4));
		centrifuge = new Research("centrifuge", new ItemStack(FactoryInit.Centrifuge)).setResearchTime(2000).addParent(multiblockComponents).addRequiredItem(new ItemStack(FactoryInit.MultiblockCase)).addRequiredItem(CraftingMaterial.NORMAL_CIRCUIT.getStackNormal(4)).addRequiredItem(TMResource.ALUMINUM.getBlockStackNormal(2)).addRequiredItem(CraftingMaterial.ELECTRIC_MOTOR.getStackNormal());
		plasticProcessing = new Research("plasticProcessing", CraftingMaterial.PLASTIC_SHEET.getStackNormal()).setResearchTime(2200).addParent(mvMachines).addParent(refinery).addRequiredItem(CraftingMaterial.BOTTLE_OF_RUBBER.getStackNormal(3)).addRequiredItem(new ItemStack(Items.SUGAR)).addRequiredItem(TMResource.COAL.getStackNormal(Type.GEM, 20));
		hvTransformer = new Research("hvTransformer", new ItemStack(EnergyInit.transformerMHV)).setResearchTime(2100).addParent(refinery).addParent(mvMachines).addRequiredItem(TMResource.ELECTRUM.getStackNormal(Type.COIL, 8)).addRequiredItem(TMResource.IRON.getStackNormal(Type.COIL, 3)).addRequiredItem(new ItemStack(Items.IRON_INGOT, 5)).addRequiredItem(new ItemStack(Items.REDSTONE, 16));
		hvCable = new Research("hvCable", new ItemStack(EnergyInit.hvCable)).setResearchTime(2100).addParent(hvTransformer).addRequiredItem(TMResource.IRON.getStackNormal(Type.CABLE, 10)).addRequiredItem(CraftingMaterial.RUBBER.getStackNormal(20)).addRequiredItem(new ItemStack(EnergyInit.mvCable, 4)).addRequiredItem(new ItemStack(Items.REDSTONE, 4));
		advancedMultiblockParts = new Research("advMultiblockParts", new ItemStack(FactoryInit.AdvancedMultiblockCasing)).setResearchTime(2200).addRequiredItem(new ItemStack(FactoryInit.MultiblockCase, 4)).addRequiredItem(TMResource.TUNGSTENSTEEL.getStackNormal(Type.PLATE, 5)).addRequiredItem(new ItemStack(CoreInit.MachineFrameTitanium, 2));
		advancedCircuit = new Research("advCircuit", CraftingMaterial.ADVANCED_CIRCUIT.getStackNormal()).setResearchTime(2500).addParent(hvTransformer).addParent(plasticProcessing).addRequiredItem(CraftingMaterial.NORMAL_CIRCUIT.getStackNormal(10)).addRequiredItem(TMResource.ELECTRUM.getStackNormal(Type.COIL, 10)).addRequiredItem(TMResource.ENDERIUM.getStackNormal(Type.COIL));
		hvMachines = new Research("hvMachines", new ItemStack(FactoryInit.crusher)).setResearchTime(2500).addParent(advancedCircuit).addRequiredItem(CraftingMaterial.ADVANCED_CIRCUIT.getStackNormal(3)).addRequiredItem(new ItemStack(CoreInit.MachineFrameTitanium)).addRequiredItem(TMResource.ENDERIUM.getStackNormal(Type.COIL)).addRequiredItem(new ItemStack(Items.REDSTONE, 32));
		eliteTank = new Research("eliteTank", new ItemStack(StorageInit.tankElite)).setResearchTime(1500).addParent(advancedTank).addParent(mvMachines).addRequiredItem(TMResource.TITANIUM.getStackNormal(Type.PLATE, 5)).addRequiredItem(new ItemStack(CoreInit.hardenedGlass, 5)).addRequiredItem(new ItemStack(StorageInit.tankAdv)).addRequiredItem(new ItemStack(Blocks.GLASS, 5));
		ultimateTank = new Research("ultimateTank", new ItemStack(StorageInit.tankUltimate)).setResearchTime(3000).addParent(eliteTank).addParent(hvMachines).addRequiredItem(TMResource.ENDERIUM.getStackNormal(Type.PLATE, 20)).addRequiredItem(new ItemStack(CoreInit.hardenedGlass, 10)).addRequiredItem(new ItemStack(Blocks.GLASS, 5)).addRequiredItem(new ItemStack(StorageInit.tankElite));
		limitableChest = new Research("configurableChest", new ItemStack(StorageInit.limitableChest)).setResearchTime(500).addParent(bronzeAge).addRequiredItem(new ItemStack(Blocks.CHEST, 2)).addRequiredItem(new ItemStack(Blocks.TRAPDOOR)).addRequiredItem(new ItemStack(Blocks.LEVER)).addRequiredItem(TMResource.BRONZE.getStackNormal(Type.PLATE));
		advancedExtruder = new Research("advExtruder", new ItemStack(FactoryInit.extruderModule, 1, 1)).setResearchTime(2000).addParent(mvMachines).addRequiredItem(TMResource.WOLFRAM.getStackNormal(Type.PLATE, 5)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 10)).addRequiredItem(new ItemStack(Items.DIAMOND)).addRequiredItem(CraftingMaterial.UPGRADE_FRAME.getStackNormal());
		mvTurbine = new Research("mvTurbine", new ItemStack(EnergyInit.steamTurbineMK2)).setResearchTime(1600).addParent(mvCircuit).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 4)).addRequiredItem(CraftingMaterial.NORMAL_CIRCUIT.getStackNormal()).addRequiredItem(new ItemStack(CoreInit.MachineFrameSteel)).addRequiredItem(new ItemStack(Items.REDSTONE, 16));
		charger = new Research("charger", new ItemStack(EnergyInit.charger)).setResearchTime(1500).addParent(basicLvMachines).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal()).addRequiredItem(new ItemStack(CoreInit.Battery, 2)).addRequiredItem(TMResource.COPPER.getStackNormal(Type.CABLE, 5));
		configurator = new Research("configurator", new ItemStack(CoreInit.configurator)).setResearchTime(1600).addParent(charger).addParent(lvAlloySmelter).addParent(eSolderingStation).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal(2)).addRequiredItem(new ItemStack(CoreInit.Display)).addRequiredItem(TMResource.IRON.getStackNormal(Type.PLATE, 2)).addRequiredItem(new ItemStack(Items.REDSTONE, 6));
		geoThermalBoiler = new Research("geoBoiler", new ItemStack(FactoryInit.geothermalBoiler)).addParent(steelBoiler).setResearchTime(800).addRequiredItem(new ItemStack(FactoryInit.advBoiler)).addRequiredItem(new ItemStack(CoreInit.MachineFrameSteel)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE)).addRequiredItem(CraftingMaterial.REFINED_BRICK.getStackNormal(4));
		geoThermalGenerator = new Research("geoGenerator", new ItemStack(EnergyInit.geothermalGenerator)).addParent(geoThermalBoiler).setResearchTime(2000).addRequiredItem(new ItemStack(FactoryInit.geothermalBoiler)).addRequiredItem(CraftingMaterial.GENERATOR_COMPONENT.getStackNormal(2)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal()).addRequiredItem(CraftingMaterial.REFINED_BRICK.getStackNormal(4));
		liquidFueledBoiler = new Research("liquidFueledBoiler", new ItemStack(FactoryInit.fluidBolier)).setResearchTime(600).addParent(basicBoiler).addRequiredItem(new ItemStack(CoreInit.MachineFrameBronze)).addRequiredItem(new ItemStack(StorageInit.tankBasic)).addRequiredItem(new ItemStack(Blocks.BRICK_BLOCK)).addParent(refinedBricks).addRequiredItem(CraftingMaterial.REFINED_BRICK.getStackNormal(3));
		liquidFueledSteelBoiler = new Research("liquidFueledAdvBoiler", new ItemStack(FactoryInit.advFluidBoiler)).setResearchTime(1200).addParent(liquidFueledBoiler).addParent(steelBoiler).addRequiredItem(new ItemStack(CoreInit.MachineFrameSteel)).addRequiredItem(TMResource.STEEL.getStackNormal(Type.PLATE, 10)).addRequiredItem(CraftingMaterial.REFINED_BRICK.getStackNormal(5));
		liquidFueledGenerator = new Research("liquidFueledGenerator", new ItemStack(EnergyInit.fluidGenerator)).setResearchTime(1600).addParent(basicLvMachines).addParent(liquidFueledSteelBoiler).addRequiredItem(new ItemStack(CoreInit.MachineFrameBasic)).addRequiredItem(CraftingMaterial.BASIC_CIRCUIT.getStackNormal(2)).addRequiredItem(new ItemStack(StorageInit.tankAdv)).addRequiredItem(CraftingMaterial.GENERATOR_COMPONENT.getStackNormal());
		registerResearch(researchAcids);
		registerResearch(researchPower);
		registerResearch(researchPower2);
		registerResearch(hammer);
		registerResearch(mortar);
		registerResearch(bronzeAge);
		registerResearch(basicBoiler);
		registerResearch(basicBronzeMachines);
		registerResearch(bronzeAlloySmelter);
		registerResearch(bronzePlateBlender);
		registerResearch(refinedBricks);
		registerResearch(cokeOven);
		registerResearch(blastFurnace);
		registerResearch(steelBoiler);
		registerResearch(steelFurnace);
		registerResearch(rubberProcessing);
		registerResearch(basicTurbine);
		registerResearch(soldering);
		registerResearch(multimeter);
		registerResearch(lvCable);
		registerResearch(batteryBox);
		registerResearch(basicLvMachines);
		registerResearch(wireProcessing);
		registerResearch(speedUpgrade);
		registerResearch(lvPlateBlender);
		registerResearch(lvAlloySmelter);
		registerResearch(waterCollector);
		registerResearch(eSolderingStation);
		registerResearch(industrialBlastFurnace);
		registerResearch(pump);
		registerResearch(fluidTransposer);
		registerResearch(advancedTank);
		registerResearch(solarPanel);
		registerResearch(mvTransformer);
		registerResearch(mvCable);
		registerResearch(mvCircuit);
		registerResearch(mvMachines);
		registerResearch(refinery);
		registerResearch(multiblockComponents);
		registerResearch(electrolyzer);
		registerResearch(centrifuge);
		registerResearch(plasticProcessing);
		registerResearch(hvTransformer);
		registerResearch(hvCable);
		registerResearch(advancedMultiblockParts);
		registerResearch(hvMachines);
		registerResearch(eliteTank);
		registerResearch(ultimateTank);
		registerResearch(limitableChest);
		registerResearch(advancedExtruder);
		registerResearch(mvTurbine);
		registerResearch(charger);
		registerResearch(configurator);
		registerResearch(geoThermalBoiler);
		registerResearch(geoThermalGenerator);
		registerResearch(liquidFueledBoiler);
		registerResearch(liquidFueledSteelBoiler);
		registerResearch(liquidFueledGenerator);
	}
	private static void registerResearch(Research research){
		research.setPrefix("tomsmod.");
		research.setRegistryName(research.getName());
		GameRegistry.register(research);
	}
}
