// Date: 2016.03.18. 15:20:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.tom.transport.model;

import java.util.HashMap;
import java.util.Map;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBelt extends ModelBase {
	// fields
	Map<Integer, ModelRenderer> beltModel;

	public ModelBelt() {
		textureWidth = 256;
		textureHeight = 256;
		beltModel = new HashMap<>();
		for (int i = 0;i <= 64;i++) {
			ModelRenderer belt;
			belt = new ModelRenderer(this, 0, i);
			// belt.addBox(0F, 0F, 0F, 14, 1, 16);
			belt.addBox(0F, 0F, 0F, 56, 4, 64);
			// belt.setRotationPoint(-7F, 18F, -8F);
			belt.setRotationPoint(-28F, 72F, -32F);
			belt.setTextureSize(256, 256);
			belt.mirror = true;
			setRotation(belt, 0F, 0F, 0F);
			beltModel.put(i, belt);
		}
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}

	public void render(int state, float f) {
		beltModel.get(state).render(f / 4);
	}
}